services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # Volume mapping giúp bạn sửa code Python trên máy, server tự cập nhật mà không cần build lại

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend